# Generated by Django 3.1.3 on 2021-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
