# Generated by Django 3.1.3 on 2021-01-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timeStamp',
        ),
    ]
